@startuml

actor Consumer
control Website
control API
control AWS_Lambda_Function
participant ProjectRepository
database DynamoDb

Consumer --> Website : Create Random Character (Roll)
Website --> API : HTML call to the API
API --> AWS_Lambda_Function : Send GET request
AWS_Lambda_Function --> ProjectRepository : Invoke method for random \ncharacter creation
ProjectRepository --> DynamoDb : Fetch requested attributes from tables (load)
DynamoDb --> ProjectRepository : Provide requested items
ProjectRepository --> AWS_Lambda_Function : Return pre-made character
AWS_Lambda_Function --> API : Send character to API
API --> Website : Delivers character to the website
Website --> Consumer : Viewer receives formatted display of character


@enduml